### ISSUE TITLE
Commands in PM are rejecting error

### ISSUE THREAD

**Issue by WlanWerner** [CharlotteDunois/Livia#25]
Hi, 
I am trying to create a Bot with livia. In Guilds it is working perfect, but if I use a command in PM the bot is crashing for every command:
``PHP Fatal error:  Uncaught RuntimeException: Unknown property CharlotteDunois\Yasmin\Models\DMChannel::$guild in /root/livia/vendor/charlottedunois/yasmin/src/Models/Base.php:57``

**Comment by CharlotteDunois** [comment]
Could you post the full stack trace?

**Comment by WlanWerner** [comment]
Sure
``PHP Fatal error:  Uncaught RuntimeException: Unknown property CharlotteDunois\Yasmin\Models\DMChannel::$guild in /root/livia/vendor/charlottedunois/yasmin/src/Models/Base.php:57
Stack trace:
#0 /root/livia/vendor/charlottedunois/yasmin/src/Models/ClientBase.php(49): CharlotteDunois\Yasmin\Models\Base->__get('guild')
#1 /root/livia/vendor/charlottedunois/yasmin/src/Models/DMChannel.php(106): CharlotteDunois\Yasmin\Models\ClientBase->__get('guild')
#2 /root/livia/vendor/charlottedunois/livia/src/Commands/Context.php(231): CharlotteDunois\Yasmin\Models\DMChannel->__get('guild')
#3 /root/livia/vendor/react/promise/src/Promise.php(245): CharlotteDunois\Livia\Commands\Context->CharlotteDunois\Livia\Commands\{closure}(Object(Closure), Object(Closure), Object(Closure))
#4 /root/livia/vendor/react/promise/src/Promise.php(25): React\Promise\Promise->call(NULL)
#5 /root/livia/vendor/charlottedunois/livia/src/Commands/Context.php(391): React\Promise\Promise->__construct(NULL)
#6 /root/livia/vendor/charlottedunois/livia/src/CommandDispatch in /root/livia/vendor/charlottedunois/eventemitter/src/EventEmitterErrorTrait.php on line 48
``

**Comment by CharlotteDunois** [comment]
Thanks for reporting, this is fixed with 24c9412.

**Comment by CharlotteDunois** [comment]
v0.4.2 is now also released.
