### ISSUE TITLE
Bot getting stuck when using args

### ISSUE THREAD

**Issue by WlanWerner** [CharlotteDunois/Livia#26]
Hi again, 
the bot is getting stuck on the commands with args, I attached a picture as example. Or am I using it wrong? 
![Desktop Screenshot 2019 07 20 - 10 33 03 67](https://user-images.githubusercontent.com/38541809/61576393-ef3eb480-aad9-11e9-8dad-527ba8e9a84f.png)

**Comment by CharlotteDunois** [comment]
The issue is probably blocking code in your bot, that prevents the event loop from running. But I can't say anything certain without code.

![grafik](https://user-images.githubusercontent.com/4529744/61576429-493f7a00-aada-11e9-9da2-14c0d00c6964.png)

**Comment by WlanWerner** [comment]
Hmm okay, I will check my code. But I didn't change anything on the code besides adding my commands, strange

**Comment by WlanWerner** [comment]
I really don't know where the error could be... The Bot is receiving my message, i see that in the CLI.
Is there any setting/poperties which have to be set to makr args working?

**Comment by WlanWerner** [comment]
Okay, this is weird but I have a workaround, that's all
``$client->on('debug', function($message){
	echo $message . PHP_EOL;
});

$client->on("error", function(\Throwable $error){
	echo $error->getMessage() . PHP_EOL;
});``

I tried to debug with that and when adding this lines to the Code it is working, than I removed them and it isn't working anyomre...
