### ISSUE TITLE
Works only a second and then closes.

### ISSUE THREAD

**Issue by Nereg** [CharlotteDunois/Livia#27]
Hello ! I just started using your framework. And when I run Your  example in CLI it works one second and then closes. Without any errors or even output! What I`m doing wrong ? I wrote all ID`s and keys correctly.

**Comment by CharlotteDunois** [comment]
If you're on windows, it might be related to <https://github.com/CharlotteDunois/Yasmin#windows-and-ssl>.

**Comment by Nereg** [comment]
No I`m not on Windows. I`m runing in Linux with Nginx

**Comment by CharlotteDunois** [comment]
Just to be clear, you can not run a bot inside a webserver. Regardless of that, I still think it's the same certificates issue (although I've never seen this on Linux), since it has the same behaviour as exiting after one loop turn.

I can not reproduce this issue with the exact example of the readme. I get the expected output from the `ready` event handler and the bot keeps running.

**Comment by Nereg** [comment]
I run bot in CLI. And how fix this certificates issue? It doesn`t output anything even in error log.

**Comment by Nereg** [comment]
And the is my php -v if it will help you : `
root@v137029:/home/admin/web/mystat.pp.ua/public_html/public/test# php -v
PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologi                    es
`

**Comment by CharlotteDunois** [comment]
See <https://github.com/CharlotteDunois/Yasmin#windows-and-ssl>, it works the same since we're messing with PHP's configuration.

**Comment by Nereg** [comment]
Ok I will try.

**Comment by Nereg** [comment]
No no result.

**Comment by Nereg** [comment]
I can give you my php.ini

**Comment by Nereg** [comment]
I also allowed all functions in php.ini but nothing

**Comment by Nereg** [comment]
I just see docs of library that you use in this framework and it is support only php 7.1 and not 7.2 that I use

**Comment by WlanWerner** [comment]
If you say it's closing after one second, is your loop working correctly?

**Comment by Nereg** [comment]
I run exsample. So everything must work correctly

**Comment by WlanWerner** [comment]
If you can why not trying on a brand new Server without nginx... 
When it is working there with exactly the same Code you know that it is because of teh webserver

**Comment by CharlotteDunois** [comment]
Please make sure all required extensions are installed and enabled. You can also read through this issue (from Yasmin) and follow the same steps (adding error listener, checking configuration, etc.): https://github.com/CharlotteDunois/Yasmin/issues/106

**Comment by Nereg** [comment]
Thank you ! All working.
