### ISSUE TITLE
How how to disable prompt for command arguments?

### ISSUE THREAD

**Issue by Nereg** [CharlotteDunois/Livia#31]
Hello ! I want disable argument prompt for command but I don`t know how. Can you help me ?

**Comment by CharlotteDunois** [comment]
Can you define "disable argument prompt" further? If the argument is optional, it won't be prompted if all required arguments are already provided in the command invocation message.

**Comment by Nereg** [comment]
I want to disable this message : 
![изображение](https://user-images.githubusercontent.com/47698366/61733845-5930b580-ad89-11e9-9667-3129b45ee0bb.png)

**Comment by CharlotteDunois** [comment]
The prompt can only be "disabled" by making the argument optional. This won't prevent command invocation, but you can simply check for the default value (e.g. check for `false` at the top of the method and then simply return).

**Comment by Nereg** [comment]
Ok thank you
