### ISSUE TITLE
Call to undefined function init() in \CharlotteDunois\Livia\Providers\MySQLProvider

### ISSUE THREAD

**Issue by Nereg** [CharlotteDunois/Livia#32]
Hello one more time. Im using your MySqlprovider and get this error : 
`\CharlotteDunois\Livia\Providers\MySQLProvider`
When running this code: 
`
$dbloop = React\EventLoop\Factory::create();
$factory = new React\MySQL\Factory($dbloop);
$uri = "*****:******@localhost/admin_default";
$connection = $factory->createLazyConnection($uri);
$db = new \CharlotteDunois\Livia\Providers\MySQLProvider($connection);
/*
.....
*/
$test = $db.init($client);
`
And if call `init` method like ` \CharlotteDunois\Livia\Providers\MySQLProvider::init($client);` I got `Uncaught Error: Using $this when not in object context`

**Comment by CharlotteDunois** [comment]
The README has a clear example on how to properly instantiate and set the provder. The `init` is invoked ONLY by the Livia client and NEVER by the user.

<https://github.com/CharlotteDunois/Livia#mysqlmariadb-reactmysql>

**Comment by Nereg** [comment]
Thank you ! I don`t know how I missed your README
