### ISSUE TITLE
Shard 0 sending IDENTIFY packet to WSShard 0 sending WS packet with OP code 2

### ISSUE THREAD

**Issue by Nereg** [CharlotteDunois/Livia#35]
hello ! i just faceed with one promblem. When I run bot it outputs this : 
`Registered type booleanRegistered type channelRegistered type commandRegistered type command-or-groupRegistered type floatRegistered type groupRegistered type integerRegistered type memberRegistered type roleRegistered
type stringRegistered type userRegistered group moderationRegistered group mystatRegistered group helpRegistered command moderation:clearRegistered command help:helpRegistered command MyStat:countRegistered command MyStat:leadersRegistered command MyStat:placeRegistered command mystat:loginRegistered command MyStat:testAdding request "gateway/bot" to ratelimit bucketRetrieved item from bucket "gateway"Executing item "gateway/bot"Got response for item "gateway/bot" with HTTP status code 200Shard 0 using compress context ZlibStreamShard 0 connecting to WS wss://gateway.discord.gg/?v=6&encoding=json&compress=zlib-streamShard 0 initialized compress context for shard Shard 0 connected to WSShard 0 connected to Gateway via ["gateway-prd-main-g3k1",{"micros":0.0}]Shard 0 sending IDENTIFY packet to WSShard 0 sending WS packet with OP code 2`
And then nothing. Bot not starting and no other output. And code that I running I placed there : [https://gist.github.com/Nereg/071ea10650f3f3bc39138bb4e1a69b25](url)

**Comment by CharlotteDunois** [comment]
Please refer to this comment <https://github.com/CharlotteDunois/Livia/issues/27#issuecomment-513460399>.

**Comment by Nereg** [comment]
I installed BCMath already. But I will verify this

**Comment by Nereg** [comment]
No nothing. And bcmath installed becouse I found this in `php -i` : bcmath

BCMath support => enabled

Directive => Local Value => Master Value
bcmath.scale => 0 => 0

**Comment by CharlotteDunois** [comment]
You already had the same issue in #27, how did you fix the issue there?

**Comment by Nereg** [comment]
I installed BCMath already. I will try reuploading all files.

**Comment by CharlotteDunois** [comment]
BCMath is not the only required PHP extension. Do not upload dependencies, install them through composer **on the host**. Only upload your bot's source files and everything needed, excluding the `vendor` directory and run `composer install` on the host.

**Comment by Nereg** [comment]
I also made `composer install` but i will delete vendor folder and run it again

**Comment by Nereg** [comment]
Nothing Made composer install several times but nothing

**Comment by Nereg** [comment]
I also runed exsample from README with debug output from [https://github.com/CharlotteDunois/Yasmin/issues/106](url) and nothing. There is output `Starting
Registered type boolean
Registered type channel
Registered type command
Registered type command-or-group
Registered type float
Registered type group
Registered type integer
Registered type member
Registered type role
Registered type string
Registered type user
Registered group commands
Registered group utils
Registered command commands:disable
Registered command commands:enable
Registered command commands:load
Registered command commands:reload
Registered command commands:unload
Registered command utils:eval
Registered command utils:help
Registered command utils:ping
Registered command utils:prefix
Registered group moderation
Adding request "gateway/bot" to ratelimit bucket
Retrieved item from bucket "gateway"
Executing item "gateway/bot"
Got response for item "gateway/bot" with HTTP status code 200
Shard 0 using compress context ZlibStream
Shard 0 connecting to WS wss://gateway.discord.gg/?v=6&encoding=json&compress=zlib-stream
Shard 0 initialized compress context for shard
Shard 0 connected to WS
Shard 0 connected to Gateway via ["gateway-prd-main-6nr9",{"micros":0.0}]
Shard 0 sending IDENTIFY packet to WS
Shard 0 sending WS packet with OP code 2`

**Comment by Nereg** [comment]
Nothing but I enebled error displaying and fixed error like this : PHP Warning:  pcntl_signal_dispatch() has been disabled for security reasons in /home/admin/web/mystat.pp.ua/bot/vendor/react/event-loop/src/StreamSelectLoop.php on line 232
Warning: pcntl_signal_dispatch() has been disabled for security reasons in /home/admin/web/mystat.pp.ua/bot/vendor/react/event-loop/src/StreamSelectLoop.php on line 232

**Comment by CharlotteDunois** [comment]
Making sure error reporting has the appropriate level was described [here](https://github.com/CharlotteDunois/Yasmin/issues/106#issuecomment-494069172).

If your issue is still not resolved, read **carefully** through the linked issue and make sure everything is correct. Everything critical to make Yasmin run is described there.
